kind: Deployment
apiVersion: apps/v1
metadata:
  name: checkoutservice-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: checkoutservice
spec:
  replicas: {{ .Values.checkoutservice.replicasCount }}
  strategy:
        type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: namanss/checkoutservice:{{ .Values.checkoutservice.imagetag }}
          ports:
            - containerPort: 8080
          env:
            - name: DISABLE_TRACING
              value: "true"
            - name: DISABLE_PROFILER
              value: "true"
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice-svc.{{ .Values.namespace }}.svc.cluster.local:3550
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice-svc.{{ .Values.namespace }}.svc.cluster.local:50051
            - name: PAYMENT_SERVICE_ADDR
              value: paymentservice-svc.{{ .Values.namespace }}.svc.cluster.local:50051
            - name: EMAIL_SERVICE_ADDR
              value: emailservice-svc.{{ .Values.namespace }}.svc.cluster.local:8080
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice-svc.{{ .Values.namespace }}.svc.cluster.local:7000
            - name: CART_SERVICE_ADDR
              value: cartservice-svc.{{ .Values.namespace }}.svc.cluster.local:7070
            - name: REDIS_ENABLED
              value: "{{ .Values.checkoutservice.redis }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "`128Mi"
              cpu: "200m"
---
kind: Service
apiVersion: v1
metadata:
  name: checkoutservice-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.checkoutservice.servicetype }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: checkoutservice-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: checkoutservice