kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  strategy:
        type: {{ .Values.strategy.type }}
  replicas: {{ .Values.frontend.replicasCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: namanss/frontend:{{ .Values.frontend.imagetag }}
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: productcatalogservice-svc.{{ .Values.namespace }}.svc.cluster.local:3550
          - name: CURRENCY_SERVICE_ADDR
            value: currencyservice-svc.{{ .Values.namespace }}.svc.cluster.local:7000
          - name: CART_SERVICE_ADDR
            value: cartservice-svc.{{ .Values.namespace }}.svc.cluster.local:7070
          - name: RECOMMENDATION_SERVICE_ADDR
            value: recommendationservice-svc.{{ .Values.namespace }}.svc.cluster.local:8080
          - name: SHIPPING_SERVICE_ADDR
            value: shippingservice-svc.{{ .Values.namespace }}.svc.cluster.local:50051
          - name: CHECKOUT_SERVICE_ADDR
            value: checkoutservice-svc.{{ .Values.namespace }}.svc.cluster.local:8080
          - name: AD_SERVICE_ADDR
            value: adservice-svc.{{ .Values.namespace }}.svc.cluster.local:9555
          - name: DISABLE_TRACING
            value: "true"
          - name: DISABLE_PROFILER
            value: "true"
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: 8080
      nodePort: {{ .Values.frontend.NodePort }}
  type: {{ .Values.frontend.servicetype }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: frontend-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend