kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: online-app
  namespace: argocd
spec:
  description: Project space for Online Web-Store Application
  sourceRepos:
    - '*'
  destinations:
    - namespace: prod #match the namespace in the main.yml
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: '*' #for principle of least privilage replace it with the application 'namespace'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prod
  namespace: argocd
spec:
  project: online-app
  source:
    repoURL: https://github.com/NamanSondhiya/google-microservices-DevSecOps-CD.git
    targetRevision: main
    path: kubernetes/
    helm:
      valueFiles:
        - environment/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automate:
      prune: true
      selfHeal: true
    syncOptions:
      - Create-namespace=true
      - ApplyOutOfSyncOnly=true
