apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-dev
  namespace: argocd
spec:
  project: online-app
  source:
    repoURL: https://github.com/NamanSondhiya/google-microservices-DevSecOps-CD.git
    targetRevision: main
    path: kubernetes/
    helm:
      valueFiles:
        - ../environment/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Create-namespace=true
      - ApplyOutOfSyncOnly=true
