apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-stage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/stage-resource
spec:
  project: online-app
  source:
    repoURL: https://github.com/NamanSondhiya/google-microservices-DevSecOps-CD.git
    targetRevision: main
    path: kubernetes/
    helm:
      valueFiles:
        - ../environment/stage/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Create-namespace=true
      - ApplyOutOfSyncOnly=true