namespace: application

strategy:
  type: RollingUpdate

redisCart:
  replicasCount: 1
  imagetag: alpine
  servicetype: ClusterIP

adservice:
  replicasCount: 1
  imagetag: 11
  servicetype: ClusterIP

cartservice:
  replicasCount: 1
  imagetag: 14
  servicetype: ClusterIP

currencyservice:
  replicasCount: 1
  imagetag: 3
  servicetype: ClusterIP

emailservice:
  replicasCount: 1
  imagetag: 2
  servicetype: ClusterIP

paymentservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP

productcatalogservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP

shippingservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP

recommendationservice:
  replicasCount: 1
  imagetag: 1
  servicetype: ClusterIP

checkoutservice:
  replicasCount: 1
  imagetag: 3
  servicetype: ClusterIP
  redis: true
  
frontend:
  replicasCount: 1
  imagetag: 10
  servicePort: 8080
  NodePort: 31328
  servicetype: NodePort

loadgenerator:
  replicasCount: 1
  imagetag: 5
  servicetype: ClusterIP